import json
import sys
from pathlib import Path

from forge.experimental.acp.runner import run_task
from forge.experimental.acp.specs import (
    AgentCli,
    AgentConfig,
    EvalCheck,
    ExpectedArtifact,
    PromptSpec,
    RunStatus,
    TaskSpec,
)


def _fake_codex(tmp_path: Path, mode: str) -> Path:
    script = tmp_path / f"fake_codex_{mode}.py"
    script.write_text(
        f"""#!/usr/bin/env python3
from pathlib import Path
import json
import sys

prompt = sys.stdin.read()
cwd = Path.cwd()
mode = {mode!r}

if mode == "success":
    (cwd / "answer.md").write_text("# Answer\\n\\nGenerated by fake codex.\\n", encoding="utf-8")
    print(json.dumps({{"type": "assistant_message_delta", "text": "created answer.md"}}))
    print(json.dumps({{"type": "artifact", "path": "answer.md"}}))
elif mode == "retry":
    if "Repair Request" in prompt:
        (cwd / "answer.md").write_text("# Repaired\\n", encoding="utf-8")
        print(json.dumps({{"type": "assistant_message_delta", "text": "repaired answer.md"}}))
        print(json.dumps({{"type": "artifact", "path": "answer.md"}}))
    else:
        print(json.dumps({{"type": "assistant_message_delta", "text": "first attempt incomplete"}}))
else:
    print(json.dumps({{"type": "assistant_message_delta", "text": "no artifact"}}))
""",
        encoding="utf-8",
    )
    script.chmod(0o755)
    return script


def _task(tmp_path: Path, fake_bin: Path, *, max_attempts: int = 1) -> TaskSpec:
    return TaskSpec(
        task_id="fake-codex",
        title="Fake Codex",
        cwd=tmp_path / "work",
        agent=AgentConfig(agent=AgentCli.codex, bin=str(fake_bin)),
        prompt=PromptSpec(instructions="Create an artifact", user_request="Write answer.md"),
        expected_artifacts=[ExpectedArtifact(path="answer.md", kind="markdown")],
        eval_checks=[
            EvalCheck(
                id="answer-non-empty",
                kind="command",
                command=[
                    sys.executable,
                    "-c",
                    (
                        "from pathlib import Path; p=Path('answer.md'); "
                        "raise SystemExit(0 if p.exists() and p.read_text().strip() else 1)"
                    ),
                ],
            )
        ],
        max_attempts=max_attempts,
        timeout_seconds=5,
    )


def test_run_task_success_writes_artifact_and_events(tmp_path: Path) -> None:
    task = _task(tmp_path, _fake_codex(tmp_path, "success"))

    result = run_task(task)

    assert result.status == RunStatus.succeeded
    assert result.result is True
    assert (task.cwd / "answer.md").exists()
    assert result.runs[0].event_log_path.exists()
    events = [
        json.loads(line) for line in result.runs[0].event_log_path.read_text(encoding="utf-8").splitlines()
    ]
    assert any(event["type"] == "artifact" for event in events)


def test_run_task_fails_when_required_artifact_missing(tmp_path: Path) -> None:
    task = _task(tmp_path, _fake_codex(tmp_path, "failure"))

    result = run_task(task)

    assert result.status == RunStatus.failed
    assert result.attempts == 1
    assert any(not check.passed for check in result.evaluations[0].checks)


def test_run_task_retries_with_repair_prompt(tmp_path: Path) -> None:
    task = _task(tmp_path, _fake_codex(tmp_path, "retry"), max_attempts=2)

    result = run_task(task)

    assert result.status == RunStatus.succeeded
    assert result.attempts == 2
    assert result.evaluations[-1].passed
    assert (task.cwd / "answer.md").read_text(encoding="utf-8").strip() == "# Repaired"
